system:
  debug: true
perspective:
  username: goose160
  change-interval: 5minutes
  automatically-enabled: true
  clear-chat: true
  night-vision:
    light-level: 10
    length-in-seconds: 30
hooks:
  essentials:
    enabled: true
