name: TrailingPerspective
main: com.graywolf336.trailingperspective.TrailingPerspectiveMain
version: maven-version-number
authors: [graywolf336]
softdepend: [WorldEdit, Vault, Essentials]
load: POSTWORLD
commands:
  togglebeingtrailer:
    description: Toggles you being a trailer of others perspectives.
  togglebeingmobtrailer:
    description: Toggles being a mob trailer.
  settrailerhome:
    description: Sets the home for all of the trailers.
  switchperspective:
    description: Flags the trailer to have their perspective switched.
  forcetrailerhome:
    description: Forces a trailer to go home and stay there.
  perspectiveblacklist:
    description: Manages the blacklist of perspectives
permissions:
  trailingperspective.togglebeingtrailer:
    default: op
  trailingperspective.togglebeingmobtrailer:
    default: op
  trailingperspective.settrailerhome:
    default: op
  trailingperspective.switchperspective:
    default: op
  trailingperspective.switchperspective.others:
    default: op
  trailingperspective.blacklist:
    default: op
