name: TrailingPerspective
main: com.graywolf336.trailingperspective.TrailingPerspectiveMain
version: maven-version-number
authors: [graywolf336]
softdepend: [WorldEdit, Vault]
load: POSTWORLD
commands:
  togglebeingtrailer:
    description: Toggles you being a trailer of others perspectives.
  settrailerhome:
    description: Sets the home for all of the trailers
permissions:
  trailingperspective.togglebeingtrailer:
    default: op
  trailingperspective.settrailerhome:
    default: op